Updated AboutUs and Individual Project Portfolio Page
AY2223S1-CS2103T-T10-3/tp pull request #7
Opened 2022-09-28 14:50 UTC by tienyu2000

2022-09-28 14:59 UTC, rylzxc commented
Yo, can change the _Updated_ to _Update_ for the title of the PR, to follow standard conventions for Git commit messages, thanks!!

Otherwise, LGTM!

2022-09-28 15:01 UTC, jacobkwan requested changes
Do change the file name for your PPP and also change your Commit Subject to adhere to the coding standard (attached below), other than that LGTM!
https://se-education.org/guides/conventions/git.html#commit-message-subject

2022-09-28 15:17 UTC, jacobkwan commented on docs/team/tienYu.md
> +#### Contributions to Developer's Guide
Nitpick but this should be Developer instead of Developer's

2022-09-29 12:13 UTC, rylzxc submitted a review, later dismissed

2022-09-29 12:13 UTC, rylzxc commented on docs/team/tienyu2000.md
> +# Tien's Project Portfolio Page
```suggestion
---
layout: page
title: Tien's Project Portfolio Page
---
```

2022-09-29 13:01 UTC, rylzxc approved these changes
LGTM

2022-09-29 13:05 UTC, jacobkwan approved these changes

2022-09-29 13:05 UTC, merged